### ISSUE TITLE
Elastic Search failed to start

### ISSUE THREAD

**Issue by dixonsiu** [personium/ansible#144]
```
[root@pds ~]# systemctl -l status elasticsearch
* elasticsearch.service - Elasticsearch
   Loaded: loaded (/etc/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-10-27 07:48:19 JST; 15s ago
     Docs: http://www.elastic.co
  Process: 4068 ExecStart=/opt/elasticsearch-6.6.1/bin/elasticsearch (code=exited, status=1/FAILURE)
 Main PID: 4068 (code=exited, status=1/FAILURE)

Oct 27 07:48:18 pds.hoge.org elasticsearch[4068]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.1.jar:6.6.1]
Oct 27 07:48:18 pds.hoge.org elasticsearch[4068]: ... 6 more
Oct 27 07:48:19 pds.hoge.org elasticsearch[4068]: [2020-10-27T07:48:19,115][INFO ][o.e.n.Node               ] [pds.hoge.org] stopping ...
Oct 27 07:48:19 pds.hoge.org elasticsearch[4068]: [2020-10-27T07:48:19,121][INFO ][o.e.n.Node               ] [pds.hoge.org] stopped
Oct 27 07:48:19 pds.hoge.org elasticsearch[4068]: [2020-10-27T07:48:19,122][INFO ][o.e.n.Node               ] [pds.hoge.org] closing ...
Oct 27 07:48:19 pds.hoge.org elasticsearch[4068]: [2020-10-27T07:48:19,136][INFO ][o.e.n.Node               ] [pds.hoge.org] closed
Oct 27 07:48:19 pds.hoge.org elasticsearch[4068]: [2020-10-27T07:48:19,139][INFO ][o.e.x.m.p.NativeController] [pds.hoge.org] Native controller process has stopped - no new native processes can be started
Oct 27 07:48:19 pds.hoge.org systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Oct 27 07:48:19 pds.hoge.org systemd[1]: Unit elasticsearch.service entered failed state.
Oct 27 07:48:19 pds.hoge.org systemd[1]: elasticsearch.service failed.
```

**Comment by tochi-y** [comment]
I changed `node.name`, but this is just name. It may not be related this issue.

In the other environment, `journalctl -b | less` shows the following error.

```
10月 27 11:28:17 localhost.localdomain elasticsearch[19346]: [2020-10-27T11:28:17,802][INFO ][o.e.d.DiscoveryModule    ] [localhost.localdomain] using discovery type [zen] and host providers [settings]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: [2020-10-27T11:28:18,230][INFO ][o.e.n.Node               ] [localhost.localdomain] initialized
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: [2020-10-27T11:28:18,230][INFO ][o.e.n.Node               ] [localhost.localdomain] starting ...
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: [2020-10-27T11:28:18,321][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [localhost.localdomain] uncaught exception in thread [main]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:enp2s0f0 (enp2
s0f0)]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: Caused by: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:enp2s0f0 (enp2s0f0)]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:184) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:218) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:192) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:108) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:373) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:136) ~[?:?]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.doStart(SecurityNetty4Transport.java:98) ~[?:?]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.doStart(SecurityNetty4ServerTransport.java:43) ~[?:?]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:65) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.transport.TransportService.doStart(TransportService.java:229) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:65) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.node.Node.start(Node.java:716) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:269) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.1.jar:6.6.1]
10月 27 11:28:18 localhost.localdomain elasticsearch[19346]: ... 6 more
```

This error may occurs by `network.host` settings. But I don't know the reason and investigating now.

**Comment by tochi-y** [comment]
temporary fix:

```
# /opt/elasticsearch/conf/elasticsearch.yml
network.host: 0.0.0.0
```
